### ISSUE TITLE
EndView에서 Class 마다 다르게 출력하기에 대하여 

### ISSUE THREAD

**Issue by kingdomunder** [kingdomunder/0823projectMini3#7]
![image](https://user-images.githubusercontent.com/85289172/130555077-3de37690-6184-417d-8352-89567f5efcc6.png)

**Comment by kingdomunder** [comment]
잘못했네요 if문 3개가 다 돌아가버려서 다시 테스트했는데 이렇게나오네요

![image](https://user-images.githubusercontent.com/85289172/130555640-82cf271f-0776-4212-a7b2-4e783ff77ec1.png)

**Comment by kingdomunder** [comment]
클래스가` List = List<Student> = List<Study> = List<Attendacne> `
전부 타입이 같은가봐요... 왜지...

리스트안에서 첫번째 원소 꺼내서 해당 타입을 비교해봐야겠네요

**Comment by seojuyn** [comment]
else if / else 로 해보시면 어떨까요 ???

**Comment by kingdomunder** [comment]
> else if / else 로 해보시면 어떨까요 ???

밥먹고 한번 시도해보겠습니다!!ㅋㅋㅋㅋ

**Comment by seojuyn** [comment]
ㅋㅋㅋ엡 맛점하세요 ~~!

**Comment by kingdomunder** [comment]
이렇게 먼저 시도해봤는데 일단 성공은 한거같습니다

1. getAllStudent() 메소드 실행 
2. 가져온 list 클래스타입은 `List<Student>`
3. list의 0번 인덱스 원소의 클래스타입은 Student
4. if문으로 클래스타입이 Student이면 print1

결론 : if문안에서 조건에 해당하는 클래스타입마다 get메소드 사용하면 되겠죠?

단점 : 비교만을 위한 변수 abc가 불필요하게 생성된다

![image](https://user-images.githubusercontent.com/85289172/130557615-1cd9e59e-c8b3-4254-a82e-fa4e22b2b2f2.png)
